### ISSUE TITLE
Modal does not animate out

### ISSUE THREAD

**Issue by Christofon** [colorfy-software/react-native-modalfy#103]
As you can see in this [Snack](https://snack.expo.dev/ZYQ8KdQQY) the modal does not animate out. 

I am using version 0.3.4.

**Comment by CharlesMangwa** [comment]
hey @Christofon! thanks a lot for adding a snack to your issue! [`v.3.4.0`](https://github.com/colorfy-software/react-native-modalfy/releases/tag/v3.4.0) didn't totally fix the problem as you've mentioned in #96. 
that being said, i think i've located the root cause and am testing the fix right now. `v.3.5.0` should be available soon and will hopefully address this issue once and for all!
