### ISSUE TITLE
Unable to override backdropOpacity and backButtonBehavior

### ISSUE THREAD

**Issue by m-ramp** [colorfy-software/react-native-modalfy#15]
Hi, great library, just what I was looking for!
From the docs, I read that options could be overridden  through:
1. static modalOptions
2. modal specific options
3. defaultOptions

in the same order of priority. However `backdropOpacity` and `backButtonBehavior` is always being picked from number 3.

checked the code in `ModalStack.js` `const {
      stack: {
        defaultOptions: { backdropOpacity },
      },
    } = this.props`
and it is intentionally picked from defaultOptions, is this a bug or is this how it is supposed to work ?

**Comment by CharlesMangwa** [comment]
Hi @m-ramp! Thanks for the support and the heads up! 

You're right about the 2 points you raised - the way Options work and `backdropOpacity` & `backButtonBehavior` missing. But that's intentional because as of now, changing these 2 values on the fly (aka per modal pretty much) would lead to some visual discrepancies we didn't tackle yet.

If you want to play with it and maybe submit a pull request, please do!

**Comment by m-ramp** [comment]
Thanks. Will see what I can do!

**Comment by CharlesMangwa** [comment]
Hey @m-ramp! Just wanted to let you know that Modalfy v2 just shipped with per modal support for `backdropOpacity` & `backBehavior` amongst other pretty nice features!  You can check out the blog post over here whenever you'll have a moment: https://colorfy-software.gitbook.io/react-native-modalfy/blog/modalfy-v2!

**Comment by m-ramp** [comment]
Thats great! will try it out in my next project.
