### ISSUE TITLE
Setting up a closing animation different from the opening animation?

### ISSUE THREAD

**Issue by MaxKebeDBZ** [colorfy-software/react-native-modalfy#152]
I'd like to set up a modal system where the first modal to open should slide up into view from the bottom of the screen, then if we open any number of modals while at least 1 modal is already showing the current modal would slide off screen to the left and the new modal replacing it would slide on screen from the right. And when closing all modals, the last visible one would slide off screen to the bottom.

The docs for the [transitionOptions](https://colorfy-software.gitbook.io/react-native-modalfy/api/types/modaloptions#transitionoptions), show that the inputRange array allows to set a different position during the lifecycle of the modals (position 0: off screen, 1: active, 2: a 2nd modal is active). Example, if I set this to all modals:

```
import { ModalOptions } from 'react-native-modalfy'
const defaultOptions: ModalOptions = {
  transitionOptions: (animatedValue) => ({
    transform: [
      {
        translateY: animatedValue.interpolate({
          inputRange: [0, 1, 2],
          outputRange: [screenHeight, 0, 0],
        }),
      },
      {
        translateX: animatedValue.interpolate({
          inputRange: [0, 1, 2],
          outputRange: [0, 0, -screenWidth],
        }),
      },
    ],
  }),
// ... other options
}
```

the first modal to open pops up from the bottom, and go to the left when replaced by another modal. But this other modal pops up from the bottom as well, I want it to come from the right.

I tried setting different transitionOptions for the modal that I know will be opened second. Example here: the LoginModal will always be called first, and the RegisterModal will only show on an action done in the LoginModal and will replace it.

```
import { ModalStackConfig } from 'react-native-modalfy'
const modalConfig: ModalStackConfig = {
  LoginModal: {
    modal: LoginModal,
    transitionOptions: (animatedValue) => ({
      transform: [
        {
          translateY: animatedValue.interpolate({
            inputRange: [0, 1, 2],
            outputRange: [screenHeight, 0, 0],
          }),
        },
        {
          translateX: animatedValue.interpolate({
            inputRange: [0, 1, 2],
            outputRange: [0, 0, -screenWidth],
          }),
        },
      ],
    }),
    // ... other options
  },
  RegisterModal: {
    modal: RegisterModal,
    transitionOptions: (animatedValue) => ({
      transform: [
        {
          translateX: animatedValue.interpolate({
            inputRange: [0, 1, 2],
            outputRange: [screenWidth, 0, -screenWidth],
          }),
        },
      ],
    }),
    // ... other options
  },
}
```

LoginModal does what is expected but RegisterModal disappears to the right of the screen. I want it to disappear to the bottom of the screen but since closing a modal reverts it back to the '0' of the array `inputRange: [0, 1, 2]` it seems the closing animation has to be the same as the opening animation (just played reversed).

So my question is: Can we have a closing animation different from the opening animation in order to make this ^ work? Or is there an entirely different set up I should do to achieve the effect I want?

**Comment by CharlesMangwa** [comment]
hey @MaxKebeDBZ! unfortunately, what you're trying to achieve is currently not quite possible: there's no proper way to have different `transitionOptions` depending on if you're opening or closing a modal, they're indeed played reversed.

the only workaround i can suggest would be to 1. use your 2nd snippet and 2. manually animate your last modal down (`RegistrationModal` in your example) _before_ you call the modalfy closing method of your choice. just don't forget to end your manual animation with an `opacity: 0` so that modalfy's doesn't cause any visual discrepancy.

sorry i can't offer a more elegant solution.. 😕

**Comment by CharlesMangwa** [comment]
hey @MaxKebeDBZ! unfortunately, what you're trying to achieve is currently not quite possible: there's no proper way to have different `transitionOptions` depending on if you're opening or closing a modal, they're indeed played reversed.

the only workaround i can suggest would be to 1. use your 2nd snippet and 2. manually animate your last modal down (`RegistrationModal` in your example) _before_ you call the modalfy closing method of your choice. just don't forget to end your manual animation with an `opacity: 0` so that modalfy's doesn't cause any visual discrepancy.

sorry i can't offer a more elegant solution... 😕

**Comment by CharlesMangwa** [comment]
hey @MaxKebeDBZ! unfortunately, what you're trying to achieve is currently not quite possible: there's no proper way to have different `transitionOptions` depending on if you're opening or closing a modal, they're indeed played reversed.

the only workaround i can suggest would be to 1. use your 2nd snippet and 2. manually animate your last modal down (`RegistrationModal` in your example) _before_ you call the modalfy closing method of your choice. just don't forget to end your manual animation with an `opacity: 0` so that modalfy's doesn't cause any visual discrepancy.

sorry i can't offer a more elegant solution.. 😕

**Comment by MaxKebeDBZ** [comment]
That's ok, thank you for the workaround I'll try to implement it.
