### ISSUE TITLE
Questions : How to implement react-native-modalfy on a global modal which is only use for modal's basic wrapper and having children for the modal's real content?

### ISSUE THREAD

**Issue by steven278** [colorfy-software/react-native-modalfy#159]
Hi, may I know, does applying the react-native-modalfy on a global modal (a modal which is called by every page who wants to use a modal and pass children as props to this global modal) is possible? Because i've tried some way to implement it and somehow the children of my modal is separated from the global modal which has applied the react-native modalfy.  

I have another question too. related to the modal params, because I've tried also to pass the modal params to my code before, but it was ended up an error (the modal, closeModal & params are undefined).  I do believe from your docs, this way of passing modal params is allowed, but idk why i can't use this approach (an example from your docs) :

```tsx
import React from 'react'
import { Button, Text, View } from 'react-native'

const ErrorModal = ({ modal: { closeModal, params } }) => (
  <View>
    <Text>An error occured!</Text>
    <Text>{params.message}</Text>
    <Button onPress={closeModal} title="OK" />
  </View>
)

export default ErrorModal
```

Do you have any idea why such a thing can happen? I also have 1 more question. actually how can i open and close the modal without using openModal & closeModal? is there any other alternative way? so i can just use my modal like this ?

```tsx
<Modal isVisible={isWarningPopUpVisible}>
  <Container
    headerBar={<></>}
    contentContainerStyle={{
      flexGrow: 1,
      justifyContent: `center`,
      padding: spacing.xTiny,
    }}
  >
    <View
      style={{
        justifyContent: `center`,
        alignItems: `center`,
        padding: spacing.xTiny,
        paddingBottom: spacing.small,
        borderRadius: spacing.xTiny,
        backgroundColor: theme.colors.onBackground,
      }}
    >
    .....
    </View>
  </Container>
</Modal>
```
  
  Thank you very much for your attention 👍

**Comment by CharlesMangwa** [comment]
hey @steven278! i'll try to answer your 3 questions here:

> does applying the react-native-modalfy on a global modal (a modal which is called by every page who wants to use a modal and pass children as props to this global modal) is possible?

yes, it is possible! ✅ you can simply create your "global" modal (ie: `<GlobalModal />`) and call it from wherever in you code with `openModal('GlobalModal', { /* any param you want to provide */ })`.

>  I do believe from your docs, this way of passing modal params is allowed, but idk why i can't use this approach (an example from your docs)

not quite! the snippet you provided is indeed how your modal can _use_ the `params`. however, you did not specify how you're opening the modal: that's where you provide `params`! Eg: `openModal('ErrorModal', { message: 'Something went wrong...' })`

> actually how can i open and close the modal without using openModal & closeModal? is there any other alternative way? so i can just use my modal like this ?

that is not possible with modalfy. the whole philosophy of the library is to _**not**_ have what you wrote in your snippet. if you prefer such api, you might want to consider using[ react native's default modal component](https://reactnative.dev/docs/modal), rather than this library. 

if not, i'd suggest you [read the documentation](https://colorfy-software.gitbook.io/react-native-modalfy) carefully as the questions you raised are all covered there. if you've already done if, i'd recommend another run just in case. of course, if anything is not clear in there: please feel free to let me know!
