### ISSUE TITLE
Need Help! dialog shown behind react native modal

### ISSUE THREAD

**Issue by jaydengwe** [colorfy-software/react-native-modalfy#162]
Hi, thanks for your amazing work, this lib is great!

I switched to this lib a few months ago, because the official modal can't nested multiple modals at the same time.

But now, I am facing another issue that I want to openModal when there is already an official modal on the screen.

The modal opened by openModal is behind the official modal, any ideas regarding this issue?

Thanks!

**Comment by CharlesMangwa** [comment]
hey @jaydengwe! thanks for the kind words! modalfy's modals are rendered via javascript while react native's modal is actually using [the native platform modal](https://github.com/facebook/react-native/blob/30e75a51f3af7fbad83e4b002526b69bba021753/packages/react-native/React/Views/RCTModalHostView.h) (that's also the reason why [you can only render 1 at a time](https://github.com/facebook/react-native/issues/37198) for instance). that's why modalfy's modal are rendered underneath. so my suggestion would be to fully migrate to modalfy if possible.
