### ISSUE TITLE
StatusBarTranslucent props support

### ISSUE THREAD

**Issue by 1280103995** [colorfy-software/react-native-modalfy#34]
Now, RN Modal supports StatusBarTranslucent props, so will Modalfy follow up?

**Comment by CharlesMangwa** [comment]
Hey 1280103995, if you checked Modalfy's doc you'd have realized that this something you were able to do from the get go: you're the one who decides which components get rendered in your modal. <StatusBar /> could be one. 
With that being said: open source isn't a competition. It's not because one library has a feature that another one has to "follow".
Good luck with your projects.
