### ISSUE TITLE
calling openModal with same modal opens that modal again over previous modal

### ISSUE THREAD

**Issue by shubhamdeol** [colorfy-software/react-native-modalfy#71]
- I have a button on press of which I open a modal.
- when users clicking over button multiple times very quickly multiple instances of same modal gets created. 
- One way I can fix this by using event throttle when calling the open modal. I feel App becomes slow when modal content is more. So users pressed the modal open buttons multiple times as a results multiple instances of modal gets created.

When using Modal component shipped with React Native, It always stays in DOM and accepts the prop visible to be true or false. So it feels faster. 
But I think when using this library. You Modal Component gets added to DOM only when openModal is called.

Can we make modal opening little bit more performant?

**Comment by CharlesMangwa** [comment]
Hey @shubhamdeol! 

Regarding your 1st comment: Modalfy purposefully does not manage how many times a modal is being opened. It is actually in [our philosophy](https://github.com/colorfy-software/react-native-modalfy#-purpose) to let you: 

> 2. Display several modals at once, stack as many as you like.

That's why you indeed are the one responsible for debouncing the actions that lead to a modal opening.

Regarding your 2nd comment, this is a tradeoff we have to pay for using a JavaScript solution. As you may already know, React Native's `Modal` uses [a native](https://github.com/facebook/react-native/blob/6b42bcc1f433671e90b1ec0b67bbbab46cd9d48a/React/Views/RCTModalHostViewManager.m) [modal View](https://github.com/facebook/react-native/blob/main/React/Views/RCTModalHostView.m) under the hood. The clear advantage there is the one you mentioned: speed. The drawback - that was also a motivation for use to create Modalfy - is that: it doesn't allow you to [have multiple modals at once](https://github.com/facebook/react-native/pull/31498). Those 2 things combined make it much easier to use a single Modal and just have to update its content.

But because Modalfy doesn't know which and how many modals you'll be opening and closing, the same approach wouldn't really be a viable option for us.

However, if you already have ideas about how to make opening modals more performant: I'll be more than happy to review any PR you'd submit!
