### ISSUE TITLE
Modal doesn't scroll up when keyboard is open on iOS

### ISSUE THREAD

**Issue by nandha-kumar-hajari** [colorfy-software/react-native-modalfy#82]
I created a modal using react-native-modalfy with an input field in it. On android everything is working as expected(i.e., modal moving up when keyboard appears) but on iOS, whenever I try to type something the keyboard appears on the modal UI and doesn't allow me to see anything that happens on the modal UI. Is there any workaround to get past this issue? @CharlesMangwa

**Comment by CharlesMangwa** [comment]
Hi @nandha-kumar-hajari. As mentioned in [my reply](https://github.com/colorfy-software/react-native-modalfy/issues/63#issuecomment-1024486148) in #63 in which you posted your initial message: it is incumbent upon you to handle this.

You might want the modal to move up or down, but somebody else might want a completely different behavior (translate the modal, scale it, replace it with another component, etc). Because of all of this, we decided that **Modalfy does not and will not interfere with this in the foreseeable future**.

But once again, as mentioned in #63: you do have full control over how your modals are rendered. Modalfy only provides a _wrapper_ for you, so to speak. Therefore, feel free to implement your desired behavior via the customary `KeyboardAvoidingView`. If you want something more fine-tuned: you can always use `Keyboard.addListener` and animate your modal as you please.

**Comment by ntxl1210** [comment]
> Hi @nandha-kumar-hajari. As mentioned in [my reply](https://github.com/colorfy-software/react-native-modalfy/issues/63#issuecomment-1024486148) in #63 in which you posted your initial message: it is incumbent upon you to handle this.
> 
> You might want the modal to move up or down, but somebody else might want a completely different behavior (translate the modal, scale it, replace it with another component, etc). Because of all of this, we decided that **Modalfy does not and will not interfere with this in the foreseeable future**.
> 
> But once again, as mentioned in #63: you do have full control over how your modals are rendered. Modalfy only provides a _wrapper_ for you, so to speak. Therefore, feel free to implement your desired behavior via the customary `KeyboardAvoidingView`. If you want something more fine-tuned: you can always use `Keyboard.addListener` and animate your modal as you please.

Can you give me an example, pls?
