### ISSUE TITLE
How to have modal be on top of React Native's modal?

### ISSUE THREAD

**Issue by Darren120** [colorfy-software/react-native-modalfy#94]
Currently if I have a RN modal open, and I want to show my error modal, the error modal will be behind the RN modal. How do I make it in front? If that is not possible, how do I render a RN like modal using modalfy? thanks.

**Comment by CharlesMangwa** [comment]
hey @Darren120! that's happening because react native's own modal is using the platform-specific native modal component: that's why it's displayed on top of modalfy's modals (which are js-powered).
my advice would be to move to modalfy fully and then build the ui of your modals the way you want (ie: make it look like a default react native one).
